import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useState } from 'react';

export default function Home() {
  const [upazilaName, setUpazilaName] = useState('');
  const [instituteType, setInstituteType] = useState('');
  const [eiin, setEiin] = useState('');
  const [studentsNumber, setStudentsNumber] = useState(0); // Parse as an integer
  const [instituteName, setInstituteName] = useState('');
  const [distance, setDistance] = useState('');
  const [location, setLocation] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await fetch('/api/createInstitute', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: instituteName,
          location,
          institutesNum: studentsNumber,
          eiin,
          distance,
          upazilaName,
          instituteType,
        }),
      });

      if (response.ok) {
        const createdInstitute = await response.json();
        console.log('Institute created:', createdInstitute);
      } else {
        console.error('Error creating institute:', response.statusText);
      }
    } catch (error) {
      console.error('Error creating institute:', error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Upazila Name"
            value={upazilaName}
            onChange={(e) => setUpazilaName(e.target.value)}
          />
          <input
            type="text"
            placeholder="Institute Type"
            value={instituteType}
            onChange={(e) => setInstituteType(e.target.value)}
          />
          <input
            type="text"
            placeholder="EIIN"
            value={eiin}
            onChange={(e) => setEiin(e.target.value)}
          />
          <input
            type="number"
            placeholder="Students Number"
            value={studentsNumber}
            onChange={(e) => setStudentsNumber(parseInt(e.target.value))}
          />
          <input
            type="text"
            placeholder="Institute Name"
            value={instituteName}
            onChange={(e) => setInstituteName(e.target.value)}
          />
          <input
            type="text"
            placeholder="Distance"
            value={distance}
            onChange={(e) => setDistance(e.target.value)}
          />
          <input
            type="text"
            placeholder="Location"
            value={location}
            onChange={(e) => setLocation(e.target.value)}
          />
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  );
}
